### ISSUE TITLE
User index function.

### ISSUE THREAD

**Issue by arnoac** [hedii/Codeigniter-login-logout-register#1]
Whenever I try to change the index function in the User class to:

```
public function index() {

    $this->load->view('header');
    $this->load->view('user/profile');
    $this->load->view('footer');
}
```

It says It can't open the page, what am I doing wrong?

**Comment by hedii** [comment]
If you look at the views directory (application/views/), you will see that there is no 'profile' directory or file.
So it is normal that you cannot load the 'profile' view : it does not exist.
You have to create it. This repository is just a starter to manage user registration, login, logout. To manage user profiles, you have to write your own code.
Let me know if you have any other questions.

**Comment by arnoac** [comment]
Yeah I figured it out, atm I want to use the users avatar in the header.php file navigation. but I can't declare $user anywhere there. How would I go about doing this? and also the email verification doesn't work ( ripped that from your forum project ), maybe the email doesn't send because I'm working local atm?

**Comment by hedii** [comment]
This is basic codeigniter framework understanding. Maybe you have to look at the codeigniter documentation, especially this part: http://www.codeigniter.com/user_guide/general/views.html#adding-dynamic-data-to-the-view
To use $user in the header view, you have to pass data from the controller to the view. Something like this in your controller:

``` php
// you put user in your data object
$data->user = $this->user_model->get_user($user_id);

// you send the data object to the header view
$this->load->view('header', $data);
/* ... */
```

That way you can use $user in the header view.

For the emails, it is not available in this repository yet (it will be a pleasure if you want to make a pull request for this functionality).
If you get the code from [hedii/Codeigniter-Forum](https://github.com/hedii/Codeigniter-Forum), you have to adapt it to work with this repository.
I think you also need an smtp server (remote or local)

**Comment by arnoac** [comment]
This already happens in the User controler in the index function?
It sets all the user info to $data by 

$data->user = $user;

So i changed all the 'header' to 'header', $data but it doesn't seem to work for some pages

**Comment by hedii** [comment]
In the user controller, on this repository, the index method is empty.
see [the source code](https://github.com/hedii/Codeigniter-login-logout-register/blob/master/application/controllers/User.php)
you have to write your own method.
Maybe you should ask some help in the codeigniter's forum, because your problem is not related with this repository but with codeigniter knowledges.

**Comment by arnoac** [comment]
the index code is equal to your forum code, so it's your work? but ok thanks anyways

**Comment by hedii** [comment]
you are asking questions here about another repository, please ask on the other repository because it is very confusing asking here about another repository, i don't understand which repository you are working on.
if you mix 2 pieces of code, share it and i will help you!

**Comment by arnoac** [comment]
Well I basicly wanted the full register/login working but didn't need the Forums so I used this rep to add the basic register/login then went to the forum rep to add missing code to this rep. check the pastebins to see my user controller and user_model

User Controller
http://pastebin.com/45u5aQHy

User_model
http://pastebin.com/LV44R9RD

the sql table ( just if you were interested )
http://pastebin.com/UpqDcN8p

registering and login works, just small issues with adding the avatar for example, and the email validation

**Comment by hedii** [comment]
the forum repo has full working registration/confirmation/login/logout
It would be easier for you if you start with the forum repo and remove what you don't need.
the confirmation email will be sent with the admin email (the one you entered during the automatic installation).
It will work as is , but most of time emails will be treated as spam until you configure an smtp server with codeigniter.
To send smtp email with codeigniter, take a look at this answer on stackoverflow: http://stackoverflow.com/a/1622996/2746369
This will be the only thing you'll have to change/add.
with the forum repo as a starter, you will not have problems with avatars (the file structure of the forum repo is different).
Also, check that the server user (www-data or apache) has read/write permission to the avatar upload folder.
if you need help with the forum repo, please post an issue on the forum repo.
