### ISSUE TITLE
Run some routes without authentication

### ISSUE THREAD

**Issue by haffoudhi** [hedii/Codeigniter-login-logout-register#2]
how can i run some routes without passing by login? 
Is it related to your module, or related to codeigniter and how can i do it.
# Update:

I just found it in the router 
if(!isset($_SESSION['username']) || !$_SESSION['logged_in']) redirect('login');

**Comment by hedii** [comment]
Hi @haffoudhi 
there is no session related code in the route.php file, and i cannot find the piece of code you shared anywhere in the repository...
But i am happy you found a solution.
PS: if you want to create new pages that are not related to the user, you should create a new controller and manage sessions (login) as you want.
