### ISSUE TITLE
Form validation fails in register

### ISSUE THREAD

**Issue by grvpanchal** [hedii/Codeigniter-login-logout-register#3]
Whenever I submit form, the database only adds a session and fails to add user. Every time I get 

["__ci_last_regenerate"]=> int(session_no)

**Comment by hedii** [comment]
I cannot reproduce it, everything is fine when i test with the code as is.

Please verify your database connection settings in /application/config/database.php
You have to change it to match your database server.

**Comment by hedii** [comment]
I close, reopen if you need it
