### ISSUE TITLE
session issues

### ISSUE THREAD

**Issue by tamas-hamszabo** [hedii/Codeigniter-login-logout-register#7]
When user logs in session is created and but when navigating to another page session data is not available any more. I am confident the code is perfect, but what else can cause this issue?

**Comment by tamas-hamszabo** [comment]
update: Codeigniter generates new session id on every page load. Any idea how to fix that?
http://stackoverflow.com/questions/41269047/codeigniter-new-session-id-on-each-page-load

**Comment by hedii** [comment]
I really have no idea... Honestly, i do not use Codeigniter anymore
